all:
  children:
    proxmox_hosts:
      hosts:
        pve:
          # IP Address Proxmox Host
          ansible_host: 192.168.100.200
          # Proxmox Node Name eg pve
          proxmox_node: pve
      vars:
        # Backup Storage Name eg local, usbBCK
        backup_storage: usbBCK
        # Proxmox Username connected to API eg "user@pve"
        proxmox_api_user: "ansible@pve"
        # Proxmox API Token ID eg "ansible"
        proxmox_api_token_id: "ansible"
        # Proxmox API Token Secret
        proxmox_api_token_secret: "a39918e5-6d49-4d74-a7fd-224a7964359b"

